### ISSUE TITLE
404 error assistance

### ISSUE THREAD

**Issue by pbradl42** [NYPL/libbib#16]
Hello - I'm new to libraries, but competent in R.  I'm getting a 404 error on worldcat_api_search:

`worldcat_api_search('($dewey="17*" or $lc_call="bj*") and srw.yr="18*"')
Error in worldcat_api_get_http_response(fullurl, print.api.responses = debug) : 
  API returned non-OK status code 404`

I believe the proxy is working (i.e. it returned 407 before I defined the proxy correctly in my .Renviron).  Is there a function to test the connection? If not, any ideas on how can I diagnose whether the issue is proxy, API key or other?

**Comment by pbradl42** [comment]
Just following up - the problem was my API key wasn't enabled for WorldCat SearchAPI. Once I generated a new key that *was* enabled, it worked without a proxy.  Thanks!

**Comment by tonyfischetti** [comment]
I'm glad you got it sorted out! Let me know if you have any other problems or have ideas for interesting additions
